const IPSTACK = {
  LOADING: 'IPSTACK_LOADING',
  FETCH_SUCCESS: 'IPSTACK_FETCH_SUCCESS',
  FETCH_FAILED: 'IPSTACK_FETCH_FAILED'  
};

const WEATHER = {
  LOADING: 'WEATHER_LOADING',
  FETCH_DETAIL_SUCCESS: 'WEATHER_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'WEATHER_FETCH_DETAIL_SUCCESS'
}

export { IPSTACK, WEATHER };
