const IPSTACK = {
  LOADING: 'IPSTACK_LOADING',
  FETCH_SUCCESS: 'IPSTACK_FETCH_SUCCESS',
  FETCH_FAILED: 'IPSTACK_FETCH_FAILED'  
};

const WEATHER = {
  LOADING: 'WEATHER_LOADING',
  FETCH_WEATHER_SUCCESS: 'WEATHER_FETCH_WEATHER_SUCCESS',
  FETCH_WEATHER_FAILED: 'WEATHER_FETCH_WEATHER_FAILED'
}

export { IPSTACK, WEATHER };
